# Generated by Django 5.0.6 on 2024-09-24 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_medicalhistory_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='speciality',
        ),
    ]
