# Generated by Django 5.0.6 on 2024-10-09 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_appointment_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='speciality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='core.speciality'),
        ),
    ]
