# Generated by Django 5.0.6 on 2024-10-10 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_appointment_speciality'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_appointment',
        ),
    ]
