# Generated by Django 5.0.6 on 2024-10-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_appointment_unique_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='attended',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmada'), ('CANCELLED', 'Cancelada'), ('ATTENDED', 'Atendida'), ('NO_SHOW', 'No asistió')], default='CONFIRMED', max_length=20),
        ),
    ]
