# Generated by Django 5.0.6 on 2024-10-23 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_appointment_attended_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosed_histories', to=settings.AUTH_USER_MODEL),
        ),
    ]
