# Generated by Django 5.0.6 on 2024-11-09 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_medicalhistory_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_histories', to='core.appointment'),
        ),
    ]
