# Generated by Django 5.0.6 on 2024-11-09 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_medicalhistory_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_histories', to='core.appointment'),
        ),
    ]
