# Generated by Django 5.0.6 on 2024-11-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_medicalhistory_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='detailed_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
