# Generated by Django 5.0.6 on 2024-12-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_speciality_detailed_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='genre',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
