# Generated by Django 5.0.6 on 2025-01-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_user_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='instructions',
            field=models.TextField(default='No instructions provided', help_text='Indicaciones: cómo y cuándo tomar el medicamento.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medication_details',
            field=models.TextField(help_text='Detalles del medicamento: nombre, gramos, tabletas, etc.'),
        ),
    ]
