# Generated by Django 5.0.6 on 2025-01-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_prescription_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='prescriptions/'),
        ),
    ]
