# Generated by Django 5.0.6 on 2025-01-18 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_prescription_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='printed',
        ),
    ]
