# Generated by Django 5.0.6 on 2025-02-04 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_notification_rating_delete_actionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Triage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('heart_rate', models.IntegerField(verbose_name='Frecuencia Cardíaca')),
                ('respiratory_rate', models.IntegerField(verbose_name='Frecuencia Respiratoria')),
                ('systolic_blood_pressure', models.IntegerField(verbose_name='Presión Arterial Sistólica')),
                ('oxygen_saturation', models.IntegerField(verbose_name='SpO2')),
                ('consciousness_level', models.CharField(choices=[('ALERT', 'Alerta'), ('VERBAL', 'Responde a estímulo verbal'), ('PAIN', 'Responde a estímulo doloroso'), ('UNRESPONSIVE', 'No responde')], max_length=20, verbose_name='Nivel de Conciencia')),
                ('heart_rate_score', models.IntegerField(default=0)),
                ('respiratory_rate_score', models.IntegerField(default=0)),
                ('blood_pressure_score', models.IntegerField(default=0)),
                ('oxygen_saturation_score', models.IntegerField(default=0)),
                ('consciousness_score', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('NORMAL', 'Normal'), ('MODERATE', 'Alerta Moderada'), ('SEVERE', 'Alerta Severa'), ('CRITICAL', 'Crítico')], max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
